use anyhow::{Context, Result};
use std::fs;
use std::path::Path;

const AGENTS_MD_FILENAME: &str = "AGENTS.md";

use crate::utils::context::ProjectContext;
use serde::{Deserialize, Serialize};
use regex::Regex;
use chrono::Local;

const ACTIVITY_HEADING: &str = "## Agent Activity";

pub fn append_activity_to_agents_md(summary: &str) -> Result<()> {
    let path = Path::new(AGENTS_MD_FILENAME);
    if !path.exists() {
        return Ok(());
    }

    let mut content = fs::read_to_string(path)?;
    let timestamp = Local::now().format("%Y-%m-%d %H:%M:%S");
    let entry = format!("\n**{}**\n\n```json\n{}\n```\n", timestamp, summary);

    if let Some(pos) = content.find(ACTIVITY_HEADING) {
        let end_of_line = content[pos..].find('\n').unwrap_or(content.len() - pos) + pos;
        content.insert_str(end_of_line, &entry);
    } else {
        content.push_str(&format!("\n{}\n{}", ACTIVITY_HEADING, entry));
    }

    fs::write(path, content)?;
    Ok(())
}

#[derive(Debug, Serialize, Deserialize)]
pub struct AgentsMd {
    pub commands: Vec<CommandSection>,
    pub execution_confirmation: bool,
    pub trust_level: String,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct CommandSection {
    pub heading: String,
    pub commands: Vec<String>,
}

pub fn parse_agents_md(content: &str) -> AgentsMd {
    let mut commands = Vec::new();
    let mut execution_confirmation = true;
    let mut trust_level = "low".to_string();

    let heading_regex = Regex::new(r"^##\s+(.*)").unwrap();
    let command_regex = Regex::new(r"```sh\n((.|\n)*?)```").unwrap();
    let confirmation_regex = Regex::new(r"Execution-Confirmation:\s*(disabled|enabled)").unwrap();
    let trust_level_regex = Regex::new(r"Trust-Level:\s*(low|medium|high)").unwrap();

    for line in content.lines() {
        if let Some(caps) = confirmation_regex.captures(line) {
            if &caps[1] == "disabled" {
                execution_confirmation = false;
            }
        }
        if let Some(caps) = trust_level_regex.captures(line) {
            trust_level = caps[1].to_string();
        }
    }

    for cap in command_regex.captures_iter(content) {
        let preceding_text = &content[..cap.get(0).unwrap().start()];
        let mut heading = "General";

        if let Some(last_heading) = preceding_text.lines().rev().find(|l| l.starts_with("## ")) {
            if let Some(heading_cap) = heading_regex.captures(last_heading) {
                heading = heading_cap.get(1).unwrap().as_str().trim();
            }
        }

        let commands_str = cap.get(1).unwrap().as_str().trim();
        let commands_vec = commands_str.lines().map(|s| s.to_string()).collect();

        commands.push(CommandSection {
            heading: heading.to_string(),
            commands: commands_vec,
        });
    }

    AgentsMd {
        commands,
        execution_confirmation,
        trust_level,
    }
}

pub fn generate_agents_md_content(context: &ProjectContext) -> String {
    let mut content = String::new();

    content.push_str("# 🤖 AGENTS.md - Your AI's Guide to this Project\n\n");
    content.push_str("This file was auto-generated by Rainy CLI to provide context to the AI agent.\n");
    content.push_str("You can (and should!) edit this file to add more details, rules, and guidelines.\n\n");

    if !context.project_overview.is_empty() {
        content.push_str("## 🚀 Project Overview\n\n");
        content.push_str(&context.project_overview);
        content.push_str("\n\n");
    }

    if !context.tech_stack.is_empty() {
        content.push_str("## 💻 Tech Stack\n\n");
        for tech in &context.tech_stack {
            content.push_str(&format!("- {}\n", tech));
        }
        content.push_str("\n");
    }

    if !context.project_structure.is_empty() {
        content.push_str("## 📂 Project Structure\n\n");
        content.push_str("```\n");
        content.push_str(&context.project_structure);
        content.push_str("```\n\n");
    }

    if !context.build_commands.is_empty() || !context.run_commands.is_empty() || !context.test_commands.is_empty() {
        content.push_str("## ⚙️ Key Commands\n\n");
        if !context.build_commands.is_empty() {
            content.push_str("### Build\n```sh\n");
            content.push_str(&context.build_commands.join("\n"));
            content.push_str("\n```\n\n");
        }
        if !context.run_commands.is_empty() {
            content.push_str("### Run\n```sh\n");
            content.push_str(&context.run_commands.join("\n"));
            content.push_str("\n```\n\n");
        }
        if !context.test_commands.is_empty() {
            content.push_str("### Test\n```sh\n");
            content.push_str(&context.test_commands.join("\n"));
            content.push_str("\n```\n\n");
        }
    }

    if !context.key_files.is_empty() {
        content.push_str("## 📄 Key Files\n\n");
        for file in &context.key_files {
            content.push_str(&format!("- `{}`\n", file));
        }
        content.push_str("\n");
    }

    content.push_str("## 📜 Rules & Conventions\n\n");
    content.push_str("(Add your project-specific rules here. For example:)\n");
    content.push_str("- Follow PEP 8 for Python code.\n");
    content.push_str("- All new features must have unit tests.\n");
    content.push_str("- Keep components small and focused.\n");

    content
}

pub fn load_hierarchical_agents_md() -> Result<String> {
    let mut combined_content = String::new();
    let current_dir = std::env::current_dir()?;
    let home_dir = dirs::home_dir().context("Could not find home directory")?;

    let mut path = current_dir.as_path();

    loop {
        let agents_md_path = path.join(AGENTS_MD_FILENAME);
        if agents_md_path.exists() {
            let content = fs::read_to_string(&agents_md_path)?;
            combined_content.push_str(&format!(
                "\n\n---\n\n# Context from {}\n\n{}",
                agents_md_path.display(),
                content
            ));
        }

        if path == home_dir {
            break;
        }

        if let Some(parent) = path.parent() {
            path = parent;
        } else {
            break;
        }
    }

    Ok(combined_content)
}
