/*
use crate::ui;
use anyhow::{Context, Result};
use std::fs;
use std::path::Path;

const RAINY_MD_FILENAME: &str = "rainy.md";

use crate::config::Config;

pub async fn ensure_rainy_md_exists(config: &Config) -> Result<()> {
    // Heuristic to check if this is a project directory
    let is_project = Path::new(".git").exists()
        || Path::new("Cargo.toml").exists()
        || Path::new("package.json").exists()
        || Path::new("pyproject.toml").exists()
        || Path::new("pom.xml").exists();

    if !is_project {
        return Ok(()); // Not a project, so don't create rainy.md
    }

    let path = Path::new(RAINY_MD_FILENAME);
    if !path.exists() {
        ui::print_info(&format!("{} Analyzing project to generate `{}`...", ui::INFO, RAINY_MD_FILENAME));

        let context = match crate::utils::context::analyze_project(config).await {
            Ok(ctx) => ctx,
            Err(e) => {
                ui::print_warning(&format!("Could not fully analyze project for Rainy.md: {}. A default file will be created.", e));
                // Fallback to a default context if analysis fails
                crate::utils::context::ProjectContext::default()
            }
        };

        let content = generate_rainy_md_content(&context);

        fs::write(path, content)
            .context(format!("Failed to create {}", RAINY_MD_FILENAME))?;

        ui::print_success(&format!(
            "{} Created `{}` with auto-detected project context. You can edit this file to provide project-specific instructions.",
            ui::CHECK,
            RAINY_MD_FILENAME
        ));
    }
    Ok(())
}

pub fn load_hierarchical_rainy_md() -> Result<String> {
    let mut combined_content = String::new();
    let current_dir = std::env::current_dir()?;
    let home_dir = dirs::home_dir().context("Could not find home directory")?;

    let mut path = current_dir.as_path();

    loop {
        let rainy_md_path = path.join(RAINY_MD_FILENAME);
        if rainy_md_path.exists() {
            let content = fs::read_to_string(&rainy_md_path)?;
            combined_content.push_str(&format!(
                "\n\n---\n\n# Context from {}\n\n{}",
                rainy_md_path.display(),
                content
            ));
        }

        if path == home_dir {
            break;
        }

        if let Some(parent) = path.parent() {
            path = parent;
        } else {
            break;
        }
    }

    Ok(combined_content)
}

use crate::utils::context::ProjectContext;

pub fn generate_rainy_md_content(context: &ProjectContext) -> String {
    let mut content = String::new();

    content.push_str("# ☔️ Rainy.md - Your AI's Guide to this Project\n\n");
    content.push_str("This file was auto-generated by Rainy CLI to provide context to the AI agent.\n");
    content.push_str("You can (and should!) edit this file to add more details, rules, and guidelines.\n\n");

    if !context.project_overview.is_empty() {
        content.push_str("## 🚀 Project Overview\n\n");
        content.push_str(&context.project_overview);
        content.push_str("\n\n");
    }

    if !context.tech_stack.is_empty() {
        content.push_str("## 💻 Tech Stack\n\n");
        for tech in &context.tech_stack {
            content.push_str(&format!("- {}\n", tech));
        }
        content.push_str("\n");
    }

    if !context.project_structure.is_empty() {
        content.push_str("## 📂 Project Structure\n\n");
        content.push_str("```\n");
        content.push_str(&context.project_structure);
        content.push_str("```\n\n");
    }

    if !context.build_commands.is_empty() || !context.run_commands.is_empty() || !context.test_commands.is_empty() {
        content.push_str("## ⚙️ Key Commands\n\n");
        if !context.build_commands.is_empty() {
            content.push_str("### Build\n```sh\n");
            content.push_str(&context.build_commands.join("\n"));
            content.push_str("\n```\n\n");
        }
        if !context.run_commands.is_empty() {
            content.push_str("### Run\n```sh\n");
            content.push_str(&context.run_commands.join("\n"));
            content.push_str("\n```\n\n");
        }
        if !context.test_commands.is_empty() {
            content.push_str("### Test\n```sh\n");
            content.push_str(&context.test_commands.join("\n"));
            content.push_str("\n```\n\n");
        }
    }

    if !context.key_files.is_empty() {
        content.push_str("## 📄 Key Files\n\n");
        for file in &context.key_files {
            content.push_str(&format!("- `{}`\n", file));
        }
        content.push_str("\n");
    }

    content.push_str("## 📜 Rules & Conventions\n\n");
    content.push_str("(Add your project-specific rules here. For example:)\n");
    content.push_str("- Follow PEP 8 for Python code.\n");
    content.push_str("- All new features must have unit tests.\n");
    content.push_str("- Keep components small and focused.\n");

    content
}
*/
